;; -*- no-byte-compile: t; -*-
;;; .doom.d/packages.el

;;; Examples:
;; (package! some-package)
;; (package! another-package :recipe (:host github :repo "username/repo"))
;; (package! builtin-package :disable t)


(package! mu4e-alert)
(package! elfeed)
(package! pass)
(package! org-journal)
(package! avy)
(package! vuiet)
(package! company)
(package! elfeed-org)
(package! flyspell-correct-ivy)
(package! lastfm)
(package! mu4e)
(package! elfeed-goodies)
(package! magit-section)
(package! engine-mode)
(package! pinentry)
(package! visual-fill-column)
(package! org-mime)
(package! org-tree-slide)
(package! pdf-tools)
(package! link-hint)
(package! vertico)
(package! marginalia)   
(package! swiper)
(package! org-roam)
(package! info-colors)
(package! consult)
(package! flyspell-lazy)   
(package! eshell-git-prompt)
(package! markdown-mode)
(package! beacon)
